[FIX] github_connector: Remove tzinfo from github response to prevent error
{'github_create_date': datetime.datetime(2014, 9, 10, 13, 3, 33, tzinfo=tzlocal())}

ValueError: Datetime field expects a naive datetime: 2014-09-10 13:03:33+00:00

Necessary since https://github.com/PyGithub/PyGithub/commit/0177f7c51327039c8b96b7ebb2731e32b20a8eae